In [1]:
from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [5]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [9]:
from keras import models
from keras import layers

In [10]:
inputs = layers.Input(shape=(28* 28, ))
dense1 = layers.Dense(512, activation='relu')(inputs)
dense2 = layers.Dense(10, activation='softmax')(dense1)

In [11]:
network = models.Model(inputs=inputs, outputs=dense2)

In [12]:
network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [13]:
train_images.shape

(60000, 28, 28)

In [14]:
train_images = train_images.reshape((60000, 28*28))

In [15]:
train_images = train_images.astype('float32') / 255

In [16]:
test_images = test_images.reshape((10000, 28*28))

In [17]:
test_images = test_images.astype('float32') / 255

In [18]:
test_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [19]:
from keras.utils import to_categorical

In [20]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [21]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [22]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 6s 99us/step - loss: 0.2563 - acc: 0.9267
Epoch 2/5
60000/60000 [==============================] - 4s 75us/step - loss: 0.1037 - acc: 0.9691
Epoch 3/5
60000/60000 [==============================] - 4s 73us/step - loss: 0.0685 - acc: 0.9797
Epoch 4/5
60000/60000 [==============================] - 4s 75us/step - loss: 0.0505 - acc: 0.9850
Epoch 5/5
60000/60000 [==============================] - 4s 72us/step - loss: 0.0381 - acc: 0.9888


In [23]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 52us/step


In [24]:
test_loss, test_acc

(0.06555993934139842, 0.9806)

In [25]:
from keras.datasets import mnist

In [38]:
network??